// generated by react-router-hono-server/dev
import "reflect-metadata";
import { RequestContext } from "@mikro-orm/core";
import { createHonoServer } from "react-router-hono-server/node";
import { getOrm } from "./lib/server/db/index.ts";
// import { auth } from "./lib/server/auth/index.ts";

export default await createHonoServer({
  async beforeAll(app) {
    try {
      const orm = await getOrm();
      RequestContext.create(orm.em, () => {});
    } catch (error) {
      console.log(error);
    }
    app.use("*", (c, next) => {
      c.req.raw.headers.set("x-forwarded-proto", "https");
      return next();
    });
  },
});
