// generated by react-router-hono-server/dev
import { RequestContext } from "@mikro-orm/core";
import { createHonoServer } from "react-router-hono-server/node";
import { getOrm } from "./lib/server/db/index.ts";

export default await createHonoServer({
    async configure(app) {
        app.use("*", async (c, next) => {
            try {
                const orm = await getOrm();
                RequestContext.create(orm.em, () => { });
                return next()
            } catch (error) {
                console.log(error);
                return next()
            }

        });
    },
    useWebSocket: true,

});